package com.yanyi.entity;

public class CostomerPasswordDto {
   
    private Integer id;

    private String name;

    private String password;

    private String phone;
    
    public CostomerPasswordDto(){
    	super();
    }
    //修改客户密码
    public CostomerPasswordDto(Integer id, String password ) {
		 super();
		 this.id =id;
		 this.password = password;
	}
    public CostomerPasswordDto(Integer id, String name, String password, String phone ) {
		 super();
		 this.id =id;
		 this.name = name;
		 this.password = password;
		 this.phone = phone;
	}

	public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }


    
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column study_costomer.password
     *
     * @param password the value for study_costomer.password
     *
     * @mbggenerated Fri Oct 11 11:00:24 CST 2019
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column study_costomer.phone
     *
     * @return the value of study_costomer.phone
     *
     * @mbggenerated Fri Oct 11 11:00:24 CST 2019
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column study_costomer.phone
     *
     * @param phone the value for study_costomer.phone
     *
     * @mbggenerated Fri Oct 11 11:00:24 CST 2019
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

}